services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./mongoData:/data/db
  storage:
    image: redis
  counter:
    image: alexeyerpd/counter
    ports: 
     - 3002:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  lib:
    image: alexeyerpd/lib
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3002
      - MONGO_URL=mongodb://mongo:27017/lib
    depends_on:
      - storage
      - counter